server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small_square
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect


  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui



