server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small_square
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect

